import { SpeechNormalizer } from "../apps/kiosk-ui/src/services/voice/speechNormalizer";
import { ConversationalHistoryEngine } from "../apps/kiosk-ui/src/modules/history-engine/engine";

console.log("=================================================");
console.log("VOICE FLOW END-TO-END CLINICAL VERIFICATION TEST");
console.log("=================================================");

const testUtterances = [
  {
    input: "Mujhe teen din se pet mein dard hai.",
    expectedComplaint: "abdominal_pain",
    expectedDuration: "3 days"
  },
  {
    input: "Since three days I have abdominal pain.",
    expectedComplaint: "abdominal_pain",
    expectedDuration: "3 days"
  },
  {
    input: "Mere chest mein kal se pain ho raha hai.",
    expectedComplaint: "chest_pain",
    expectedDuration: "Since yesterday"
  },
  {
    input: "kuch ajeeb lag raha hai", // Ambiguous
    expectLowConfidence: true
  }
];

for (const t of testUtterances) {
  console.log(`\nTesting Utterance: "${t.input}"`);
  const norm = SpeechNormalizer.normalize(t.input);
  console.log(`  Recognized Entities:`, norm.extractedEntities);
  console.log(`  Detected Complaint: ${norm.detectedComplaint || "None"}`);
  console.log(`  Confidence Score: ${Math.round(norm.confidence * 100)}%`);
  console.log(`  Needs Confirmation: ${norm.needsConfirmation}`);
  console.log(`  Confirmation Prompt: ${norm.confirmationMessageEn}`);

  if (t.expectedComplaint) {
    if (norm.detectedComplaint !== t.expectedComplaint) {
      throw new Error(`Expected ${t.expectedComplaint}, got ${norm.detectedComplaint}`);
    }
  }

  if (t.expectedDuration) {
    if (norm.extractedEntities.duration !== t.expectedDuration) {
      throw new Error(`Expected duration ${t.expectedDuration}, got ${norm.extractedEntities.duration}`);
    }
  }

  if (t.expectLowConfidence) {
    if (!norm.needsConfirmation) {
      throw new Error("Expected low confidence confirmation trigger for ambiguous utterance!");
    }
    console.log("  -> Correctly flagged uncertainty for patient re-confirmation!");
  }
}

console.log("\n=================================================");
console.log("TESTING MULTI-TURN CONVERSATIONAL VOICE INTAKE");
console.log("=================================================");

// Patient conversational simulation
const engine = new ConversationalHistoryEngine("abdominal_pain");
console.log(`Step 1: Kiosk asks: "${engine.getCurrentQuestion()?.promptHi}"`);

// Patient answers via voice: "Dard pet ke neeche hai"
console.log(`\nPatient speaks: "Dard pet ke neeche hai"`);
const normAns1 = SpeechNormalizer.normalize("Dard pet ke neeche hai");
console.log("Recognized:", normAns1.extractedEntities);
engine.answerNaturalText("Dard pet ke neeche hai");

console.log(`Step 2: Kiosk advances & asks: "${engine.getCurrentQuestion()?.promptHi}"`);

// Patient answers via voice: "Mujhe 3 din se hai"
console.log(`\nPatient speaks: "Mujhe 3 din se hai"`);
engine.answerNaturalText("Mujhe 3 din se hai");

console.log(`Step 3: Kiosk advances & asks: "${engine.getCurrentQuestion()?.promptHi}"`);

// Patient answers food relation
console.log(`\nPatient speaks: "Khaana khane ke baad badhta hai"`);
engine.answerNaturalText("Khaana khane ke baad badhta hai");

console.log(`\nFinal Elicited State Complete: ${engine.getState().isComplete}`);
console.log("Structured Summary Draft Generated by Voice Engine:");
console.log(engine.getState().summaryDraft);

console.log("\nALL VOICE FLOW VERIFICATION TESTS PASSED SUCCESSFULLY!\n");
